version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: "crud_go"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10

  app-go:
    container_name: app-go
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DB_Username=root
      - DB_Password= 
      - DB_Port=3306
      - DB_Host=localhost
      - DB_Name=crud_go
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_mysql:
